name: classgrid

services:
  db:
    container_name: db
    image: postgres:15-alpine
    ports:
      - "2345:2345"
    env_file:
      - ./.env
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
    volumes:
      - static:/backend/static
    depends_on:
      - db

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - frontend:/frontend

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - static:/backend/static
      - frontend:/frontend
    depends_on:
      - backend

volumes:
  db-data:
  static:
  frontend: