name: classgrid

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./.config/backend/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - static:/app/static

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./.config/frontend/Dockerfile
    ports:
      - "3000:3000"

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./.config/nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - static:/app/static
    depends_on:
      - frontend
      - backend

volumes:
  static: