server {
    listen 80;
    server_name localhost;

    location /api {
        proxy_pass http://backend:8000;
    }

    location /api/static {
        alias /backend/static;
    }

    location /admin {
        proxy_pass http://backend:8000;
    }

    location / {
        root /frontend/build;
        try_files $uri /index.html;
    }
}