# Generated by Django 5.0.4 on 2024-05-04 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlotTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=10, unique=True)),
                ('lectureTiming', models.CharField(blank=True, max_length=50, null=True)),
                ('tutorialTiming', models.CharField(blank=True, max_length=50, null=True)),
                ('labTiming', models.CharField(blank=True, max_length=50, null=True)),
                ('firstCycle', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=20)),
                ('group', models.CharField(max_length=5)),
                ('kerberos', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CourseList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semesterCode', models.CharField(max_length=10)),
                ('courseCode', models.CharField(max_length=10)),
                ('totalCredits', models.FloatField()),
                ('creditStructure', models.CharField(max_length=100)),
                ('courseSlot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_slot', to='app.slottiming')),
                ('students', models.ManyToManyField(blank=True, related_name='user_courses', to='app.userdata')),
            ],
        ),
    ]
