# Generated by Django 5.0.4 on 2024-05-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='group',
            field=models.CharField(max_length=20),
        ),
    ]
