# Generated by Django 5.0.4 on 2024-05-08 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_userdata_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slottiming',
            name='firstCycle',
        ),
    ]
