# Generated by Django 5.0.4 on 2024-07-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_slottiming_firstcycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselist',
            name='labRoom',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='courselist',
            name='lectureRoom',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='courselist',
            name='tutorialRoom',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
