# Generated by Django 5.0.4 on 2024-07-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_courselist_labroom_courselist_lectureroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselist',
            name='overrideRoomChange',
            field=models.BooleanField(default=False),
        ),
    ]
