# Generated by Django 5.0.4 on 2024-07-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_courselist_overrideroomchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselist',
            name='labRoom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='courselist',
            name='lectureRoom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='courselist',
            name='tutorialRoom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
