# Generated by Django 5.0.4 on 2024-12-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
