# Generated by Django 5.0.4 on 2024-12-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_notification_semestercode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='semesterCode',
            field=models.CharField(default='2402', max_length=10),
        ),
    ]
